In [1]:
import pandas as pd  
import numpy as np  
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/Users/jeoneunceong/traditional-liquor-RS/reviews.csv')
df

Unnamed: 0  total_index      제품명                          customerID  \
0               0           12   감그린레귤러                           eunm*****   
1               1           12   감그린레귤러                              eg****   
2               2           20    감자술13                             pala***   
3               3           20    감자술13                            sldi****   
4               4           20    감자술13                         blue*******   
...           ...          ...      ...                                 ...   
15944        3417          532  희양산막걸리9   {'name': '백창화', 'nickname': None}   
15945        3418          532  희양산막걸리9  {'name': '위현수', 'nickname': '아벨라'}   
15946        3419          532  희양산막걸리9   {'name': '주경화', 'nickname': None}   
15947        3420          532  희양산막걸리9   {'name': '양혜정', 'nickname': None}   
15948        3421          532  희양산막걸리9  {'name': '오영호', 'nickname': '호호호'}   

       score                                           comments  
0        4.0                                   예상했던 맛은 아니어서 ...  
1        4.0              큰거먹다 남기는게 싫어서 조그마한 거 시켰더니 양이좀부족하네요 ㅋㅋ  
2        4.0   한달사용기감자로 만들어서 감자향이 날줄 알았는데 감자향의 거의 없네요.. 그냥 청주느낌  
3        5.0              선물용으로 구매해서 맛은 모르겠으나 포장꼼꼼히 배송빠르게 잘왔어요.  
4        4.0                                  한달사용기부드럽게 잘 넘어가요.  
...      ...                                                ...  
15944    4.5                                                  0  
15945    5.0  확확 취하는 거 빼면 다 좋은 너무맛있는 술입니다!!\n심지어 실리콘밸리 출신이시라...  
15946    4.5                             단맛이 많이 절제된 산미가 매력적입니다.  
15947    5.0                                 친구선물해줬는데 인생막걸리찾앗대요  
15948    4.0                                      배송이 빠르고 좋습니다.  

[15949 rows x 6 columns]

In [3]:
df['comments']

0                                         예상했던 맛은 아니어서 ...
1                    큰거먹다 남기는게 싫어서 조그마한 거 시켰더니 양이좀부족하네요 ㅋㅋ
2         한달사용기감자로 만들어서 감자향이 날줄 알았는데 감자향의 거의 없네요.. 그냥 청주느낌
3                    선물용으로 구매해서 맛은 모르겠으나 포장꼼꼼히 배송빠르게 잘왔어요.
4                                        한달사용기부드럽게 잘 넘어가요.
                               ...                        
15944                                                    0
15945    확확 취하는 거 빼면 다 좋은 너무맛있는 술입니다!!\n심지어 실리콘밸리 출신이시라...
15946                               단맛이 많이 절제된 산미가 매력적입니다.
15947                                   친구선물해줬는데 인생막걸리찾앗대요
15948                                        배송이 빠르고 좋습니다.
Name: comments, Length: 15949, dtype: object

In [4]:
type(df['comments'])

pandas.core.series.Series

In [5]:
review_keyword = df['comments'].to_numpy()
review_keyword

array(['예상했던 맛은 아니어서 ...', '큰거먹다 남기는게 싫어서 조그마한 거 시켰더니 양이좀부족하네요 ㅋㅋ',
       '한달사용기감자로 만들어서 감자향이 날줄 알았는데 감자향의 거의 없네요.. 그냥 청주느낌', ...,
       '단맛이 많이 절제된 산미가 매력적입니다.', '친구선물해줬는데 인생막걸리찾앗대요', '배송이 빠르고 좋습니다.'],
      dtype=object)

In [6]:
len(review_keyword)

15949

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
# 문서 v1, 문서 v2 간 유사도인 "코사인 유사도"를 구하는 함수
def cos_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    l2_norm = (np.sqrt(sum(np.square(v1))) * np.sqrt(sum(np.square(v2))))
    similarity = dot_product / l2_norm     
    
    return similarity

In [25]:
doc_list = review_keyword
print(len(doc_list))
doc_list

15949


array(['예상했던 맛은 아니어서 ...', '큰거먹다 남기는게 싫어서 조그마한 거 시켰더니 양이좀부족하네요 ㅋㅋ',
       '한달사용기감자로 만들어서 감자향이 날줄 알았는데 감자향의 거의 없네요.. 그냥 청주느낌', ...,
       '단맛이 많이 절제된 산미가 매력적입니다.', '친구선물해줬는데 인생막걸리찾앗대요', '배송이 빠르고 좋습니다.'],
      dtype=object)

In [18]:
token_final = pd.read_csv('./token_final.csv')
token_final

배송
0        사용
1       막걸리
2        소주
3        다음
4        가격
...     ...
1609     낭낭
1610    최대한
1611  아이스크림
1612  아메리카노
1613     수삼

[1614 rows x 1 columns]

In [23]:
token_final = token_final.values.tolist()

In [7]:
token_final

[['사용'],
 ['막걸리'],
 ['소주'],
 ['다음'],
 ['가격'],
 ['넘김'],
 ['도수'],
 ['느낌'],
 ['아주'],
 ['용기'],
 ['전통주'],
 ['생각'],
 ['기대'],
 ['보고'],
 ['제품'],
 ['가장'],
 ['처음'],
 ['술잔'],
 ['하나'],
 ['마음'],
 ['박스'],
 ['보기'],
 ['안동소주'],
 ['이강주'],
 ['사은'],
 ['매우'],
 ['단맛'],
 ['최고'],
 ['이번'],
 ['자주'],
 ['정도'],
 ['역시'],
 ['다시'],
 ['사진'],
 ['마시기'],
 ['다른'],
 ['리뷰'],
 ['우리'],
 ['알콜'],
 ['별로'],
 ['제일'],
 ['살짝'],
 ['와인'],
 ['한번'],
 ['상태'],
 ['완전'],
 ['덕분'],
 ['종류'],
 ['복숭아'],
 ['강쇠'],
 ['기분'],
 ['서비스'],
 ['조금'],
 ['안주'],
 ['증류주'],
 ['거의'],
 ['그냥'],
 ['먹기'],
 ['가성'],
 ['재미'],
 ['의사'],
 ['후기'],
 ['오메'],
 ['한잔'],
 ['일반'],
 ['뚜껑'],
 ['만족'],
 ['고급'],
 ['입맛'],
 ['듭니'],
 ['청주'],
 ['사람'],
 ['요즘'],
 ['예정'],
 ['사과'],
 ['디자인'],
 ['예전'],
 ['보지'],
 ['선택'],
 ['계속'],
 ['제주'],
 ['직접'],
 ['여기'],
 ['기술'],
 ['도착'],
 ['니모'],
 ['우리나라'],
 ['약간'],
 ['식당'],
 ['탄산'],
 ['마트'],
 ['상회'],
 ['호불호'],
 ['음식'],
 ['매력'],
 ['파손'],
 ['부담'],
 ['감동'],
 ['걱정'],
 ['우렁이'],
 ['보리'],
 ['취향'],
 ['감귤'],
 ['끝맛'],
 ['패키지'],
 ['추가'],
 ['술맛'],
 ['상품'],
 ['인터넷'],
 ['

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = doc_list
stop_words = token_final
vector = CountVectorizer()

print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수 기록

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
vector.fit_transform(corpus).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

{'예상했던': 9622, '맛은': 4659, '아니어서': 8518, '큰거먹다': 13095, '남기는게': 2285, '싫어서': 8281, '조그마한': 11582, '시켰더니': 8134, '양이좀부족하네요': 9134, 'ㅋㅋ': 309, '한달사용기감자로': 13839, '만들어서': 4382, '감자향이': 628, '날줄': 2274, '알았는데': 8970, '감자향의': 627, '거의': 854, '없네요': 9370, '그냥': 1618, '청주느낌': 12670, '선물용으로': 7416, '구매해서': 1429, '모르겠으나': 5282, '포장꼼꼼히': 13505, '배송빠르게': 5950, '잘왔어요': 10962, '한달사용기부드럽게': 13894, '넘어가요': 2481, '포장도': 13507, '잘해주시고': 10976, '맛도있어요': 4599, '재구매': 11036, '빠른': 6668, '배송에': 5961, '감사드립니다': 594, '감자맛인지': 621, '달짝지근': 3058, '진한맛이라': 12357, '맛나요': 4580, '받자마자': 5836, '저넉에': 11221, '반주로': 5756, '남편과': 2320, '한잔': 14088, '했어요': 14263, '색깔이': 7177, '화이트와인처럼': 14485, '밁고': 5655, '향도': 14311, '부드럽고': 6391, '은은하게': 10173, '너무': 2401, '맛있어요': 4782, '독한술을': 3406, '안좋아하는데': 8813, '여쟈가': 9486, '먹기에도': 5009, '너무좋은': 2435, '13': 28, '밖에안되요': 5737, '감자술은': 623, '처음이라': 12601, '어떨까': 9177, '했는데': 14254, '좋아요': 11729, '한두병은': 14026, '금방인데': 1719, '살걸': 6978, '그랬어요': 1643, '재주문': 11191, '하러': 13743, '올게요

In [89]:
vector.vocabulary_

{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}

In [88]:
vector.vocabulary_

{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}

## CountVectorizer

In [78]:
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
corpus = ['you know I want your love. because I love you.']
cv = CountVectorizer()

print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [ ]:
d

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
tfidfv = TfidfVectorizer().fit(corpus)
print(tfidfv.transform(corpus).toarray())
print(tfidfv.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
