#  CBF 전처리 최종 dataframe

In [4]:
pwd

'c:\\Users\\X1Carbon\\Documents\\dev\\traditional-liquor-RS'

In [5]:
import numpy as np
import pandas as pd
import csv
import re

In [72]:
df = pd.read_csv("./Naver_Liquor_Wiki/naver_wiki_product_ver4.csv")
df

Unnamed: 0  index            제품명   향기   단맛   신맛  청량감  바디감  목넘김   담백  ...  \
0             0      0  1000억막걸리프리바이오  NaN  3.0  4.0  3.0  3.0  NaN  NaN  ...   
1             1      1    1000억유산균막걸리  NaN  3.0  5.0  5.0  3.0  NaN  NaN  ...   
2             2      2  1932새싹땅콩햅쌀막걸리  NaN  2.0  2.0  3.0  5.0  NaN  NaN  ...   
3             3      3  1932새싹땅콩흑미막걸리  NaN  3.0  1.0  1.0  4.0  NaN  NaN  ...   
4             4      4           33JU  4.0  3.0  NaN  NaN  1.0  1.0  NaN  ...   
..          ...    ...            ...  ...  ...  ...  ...  ...  ...  ...  ...   
528         528    528         회곡생동동주  NaN  3.0  2.0  3.0  3.0  NaN  NaN  ...   
529         529    529         회곡생막걸리  NaN  2.0  2.0  2.0  4.0  NaN  NaN  ...   
530         530    530            흑돈주  2.0  NaN  NaN  NaN  2.0  3.0  NaN  ...   
531         531    531       희양산막걸리15  NaN  3.0  4.0  1.0  5.0  NaN  NaN  ...   
532         532    532        희양산막걸리9  NaN  2.0  3.0  2.0  3.0  NaN  3.0  ...   

      탄산    주종 도수%           용량     가격                                원재료  \
0    NaN    탁주   5        750ml   3500                         쌀,밀,누룩,정제수   
1    NaN    탁주   5        750ml   3200                         쌀,밀,누룩,정제수   
2    NaN    탁주   6        900ml    NaN        쌀,땅콩농축액,입국,효모,고과당,정제효소제,정제수   
3    NaN    탁주   6        900ml    NaN     쌀,흑미,땅콩농축액,입국,효모,고과당,정제효소제,정제수   
4    NaN   증류주  18  500ml/200ml    NaN  산양산삼,주정,결정과당,효소처리스테비아,에리스리톨,호박산,꿀   
..   ...   ...  ..          ...    ...                                ...   
528  NaN    탁주   7      1,200ml   1300         쌀,입국,누룩,아스파탐,효모,정제수,아세설팜칼륨   
529  NaN    탁주   6        750ml   1300         쌀,입국,누룩,아스파탐,효모,정제수,아세설팜칼륨   
530  NaN  기타주류  16        365ml  12000                       황칠나무,정제수,,효모   
531  NaN    탁주  15        500ml   9500                           쌀,누룩,정제수   
532  0.0    탁주   9        750ml   8000                           쌀,누룩,정제수   

    원재료키워드               제조사 키워드(thesool)                   어울리는음식(thesool)  
0     쌀,밀,            (주)국순당          NaN                               NaN  
1     쌀,밀,            (주)국순당          저도수  적당한 감칠맛과 청량미가 있어 전, 회무침과 잘 어울린다.  
2    쌀,땅콩,    (주)1932포천일동막걸리          NaN                               NaN  
3    쌀,땅콩,    (주)1932포천일동막걸리          NaN                              마늘새우  
4     꿀,삼,     농업회사법인33가주식회사          NaN                               NaN  
..     ...               ...          ...                               ...  
528     쌀,             회곡양조장          NaN                               NaN  
529     쌀,             회곡양조장          NaN                               NaN  
530    NaN  왕지케양조장(제주본초협동조합)          NaN                               NaN  
531     쌀,              두술도가         무감미료                       매콤한 볶음류의 음식  
532     쌀,              두술도가         무감미료            매콤한 닭볶음탕과 감자탕 등의 조림 요리  

[533 rows x 21 columns]

In [73]:
df = df.replace({'향기' : { float(0) : "", float(1) : "", float(2) : "", float(3) : "향기",  float(4) : "향기",float(5) : "향기"}})
df = df.replace({'단맛' : { float(0) : "", float(1) : "", float(2) : "", float(3) : "단맛",  float(4) : "단맛",float(5) : "단맛"}})
df = df.replace({'신맛' : { float(0) : "", float(1) : "", float(2) : "", float(3) : "신맛",  float(4) : "신맛",float(5) : "신맛"}})
df = df.replace({'청량감' : { float(0) : "", float(1) : "", float(2) : "", float(3) : "청량감",  float(4) : "청량감",float(5) : "청량감"}})
df = df.replace({'바디감' : { float(0) : "", float(1) : "", float(2) : "", float(3) : "바디감",  float(4) : "바디감",float(5) : "바디감"}})
df = df.replace({'목넘김' : { float(0) : "", float(1) : "", float(2) : "", float(3) : "목넘김",  float(4) : "목넘김",float(5) : "목넘김"}})
df = df.replace({'담백' : { float(0) : "", float(1) : "", float(2) : "", float(3) : "담백",  float(4) : "담백",float(5) : "담백"}})
df = df.replace({'탄닌감' : { float(0) : "", float(1) : "", float(2) : "탄닌감", float(3) : "탄닌감",  float(4) : "탄닌감",float(5) : "탄닌감"}})
df = df.replace({'탄산' : { float(0) : "", float(1) : "탄산"}})
df.head(20)

Unnamed: 0  index            제품명   향기   단맛   신맛  청량감  바디감  목넘김   담백  ...  \
0            0      0  1000억막걸리프리바이오  NaN   단맛   신맛  청량감  바디감  NaN  NaN  ...   
1            1      1    1000억유산균막걸리  NaN   단맛   신맛  청량감  바디감  NaN  NaN  ...   
2            2      2  1932새싹땅콩햅쌀막걸리  NaN            청량감  바디감  NaN  NaN  ...   
3            3      3  1932새싹땅콩흑미막걸리  NaN   단맛            바디감  NaN  NaN  ...   
4            4      4           33JU   향기   단맛  NaN  NaN            NaN  ...   
5            5      5            52C   향기   단맛  NaN  NaN            NaN  ...   
6            6      6       DMZ240km            NaN  NaN  바디감  NaN  NaN  ...   
7            7      7        g12골디락스  NaN                 바디감  NaN  NaN  ...   
8            8      8     The찾을수록시리즈  NaN   단맛       청량감       NaN  NaN  ...   
9            9      9        가덕순쌀막걸리  NaN   단맛   신맛  청량감  바디감  NaN   담백  ...   
10          10     10        가을빛레드와인  NaN        신맛  청량감       NaN  NaN  ...   
11          11     11        가평잣생막걸리  NaN            청량감  바디감  NaN  NaN  ...   
12          12     12         감그린레귤러  NaN   단맛   신맛  청량감       NaN  NaN  ...   
13          13     13         감그린스페셜  NaN   단맛   신맛  청량감  바디감  NaN  NaN  ...   
14          14     14       감그린아이스와인  NaN   단맛            바디감  NaN  NaN  ...   
15          15     15           감보드카       NaN  NaN  NaN  바디감  목넘김  NaN  ...   
16          16     16             감사  NaN            NaN       목넘김   담백  ...   
17          17     17          감아락25            NaN  NaN       NaN  NaN  ...   
18          18     18         감악산머루주  NaN   단맛   신맛  청량감  바디감  NaN  NaN  ...   
19          19     19            감이슬       NaN  NaN  NaN            NaN  ...   

     탄산     주종                                 도수%           용량     가격  \
0   NaN     탁주                                   5        750ml   3500   
1   NaN     탁주                                   5        750ml   3200   
2   NaN     탁주                                   6        900ml    NaN   
3   NaN     탁주                                   6        900ml    NaN   
4   NaN    증류주                                  18  500ml/200ml    NaN   
5   NaN    증류주                               17.50        500ml  10000   
6   NaN   기타주류                                  25        450ml    NaN   
7   NaN     탁주                                  12        500ml  12000   
8   NaN    과실주  피치14,모스카토14,애플16,감귤16,생강16,아메리카노14        360ml    NaN   
9    탄산     탁주                                   6        750ml    NaN   
10  NaN    과실주                                  14        750ml  35000   
11  NaN     탁주                                   6        750ml   1450   
12  NaN    과실주                                  12        750ml  18000   
13  NaN    과실주                                  12        750ml  25000   
14  NaN    과실주                                  10        375ml  89000   
15  NaN    증류주                                  32        375ml  14000   
16  NaN  약주/청주                                  14        375ml  15000   
17  NaN    증류주                                  25        500ml  26000   
18  NaN    과실주                                  12        360ml    NaN   
19  NaN    증류주                                  23        375ml  10000   

                                  원재료   원재료키워드             제조사 키워드(thesool)  \
0                          쌀,밀,누룩,정제수     쌀,밀,          (주)국순당          NaN   
1                          쌀,밀,누룩,정제수     쌀,밀,          (주)국순당          저도수   
2         쌀,땅콩농축액,입국,효모,고과당,정제효소제,정제수    쌀,땅콩,  (주)1932포천일동막걸리          NaN   
3      쌀,흑미,땅콩농축액,입국,효모,고과당,정제효소제,정제수    쌀,땅콩,  (주)1932포천일동막걸리          NaN   
4   산양산삼,주정,결정과당,효소처리스테비아,에리스리톨,호박산,꿀     꿀,삼,   농업회사법인33가주식회사          NaN   
5                  정제수,주정,쌀증류식소주원액,오이       쌀,   농업회사법인(주)청산녹수          NaN   
6               자연송이버섯,브랜디원액,블랙커런트,벌꿀    꿀,버섯,             솔래원          NaN   
7              정제수,멥쌀,찹쌀,누룩,종국,효모,밀함유  쌀,찹쌀,밀,   농업회사법인(주)청산녹수         무감미료   
8                사과와인,정제수,정제주정외제품별농축액      사과,       (주)한

In [74]:
df.fillna("",inplace=True)

In [75]:
df.head()

Unnamed: 0  index            제품명  향기  단맛  신맛  청량감  바디감 목넘김 담백  ... 탄산   주종  \
0           0      0  1000억막걸리프리바이오      단맛  신맛  청량감  바디감         ...      탁주   
1           1      1    1000억유산균막걸리      단맛  신맛  청량감  바디감         ...      탁주   
2           2      2  1932새싹땅콩햅쌀막걸리              청량감  바디감         ...      탁주   
3           3      3  1932새싹땅콩흑미막걸리      단맛           바디감         ...      탁주   
4           4      4           33JU  향기  단맛                       ...     증류주   

  도수%           용량    가격                                원재료 원재료키워드  \
0   5        750ml  3500                         쌀,밀,누룩,정제수   쌀,밀,   
1   5        750ml  3200                         쌀,밀,누룩,정제수   쌀,밀,   
2   6        900ml              쌀,땅콩농축액,입국,효모,고과당,정제효소제,정제수  쌀,땅콩,   
3   6        900ml           쌀,흑미,땅콩농축액,입국,효모,고과당,정제효소제,정제수  쌀,땅콩,   
4  18  500ml/200ml        산양산삼,주정,결정과당,효소처리스테비아,에리스리톨,호박산,꿀   꿀,삼,   

              제조사 키워드(thesool)                   어울리는음식(thesool)  
0          (주)국순당                                                 
1          (주)국순당          저도수  적당한 감칠맛과 청량미가 있어 전, 회무침과 잘 어울린다.  
2  (주)1932포천일동막걸리                                                 
3  (주)1932포천일동막걸리                                           마늘새우  
4   농업회사법인33가주식회사                                                 

[5 rows x 21 columns]

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Unnamed: 0       533 non-null    int64 
 1   index            533 non-null    int64 
 2   제품명              533 non-null    object
 3   향기               533 non-null    object
 4   단맛               533 non-null    object
 5   신맛               533 non-null    object
 6   청량감              533 non-null    object
 7   바디감              533 non-null    object
 8   목넘김              533 non-null    object
 9   담백               533 non-null    object
 10  탄닌감              533 non-null    object
 11  탄산               533 non-null    object
 12  주종               533 non-null    object
 13  도수%              533 non-null    object
 14  용량               533 non-null    object
 15  가격               533 non-null    object
 16  원재료              533 non-null    object
 17  원재료키워드           533 non-null    ob

In [106]:
dff = pd.DataFrame()

dff['index'] = df['index']
dff['제품명'] = df['제품명']
dff['keyword'] = df['향기'] + "," + df['단맛'] + "," + df['신맛'] + "," + df['청량감'] + "," + df['바디감'] + "," + df['목넘김']  + "," + df['담백'] + "," + df['탄닌감'] + "," + df['탄산'] + "," + df['주종'] + "," + df['원재료키워드'] + "," + df["키워드(thesool)"]
dff.head(30)

index            제품명                               keyword
0       0  1000억막걸리프리바이오           ,단맛,신맛,청량감,바디감,,,,,탁주,쌀,밀,,
1       1    1000억유산균막걸리        ,단맛,신맛,청량감,바디감,,,,,탁주,쌀,밀,,저도수
2       2  1932새싹땅콩햅쌀막걸리              ,,,청량감,바디감,,,,,탁주,쌀,땅콩,,
3       3  1932새싹땅콩흑미막걸리               ,단맛,,,바디감,,,,,탁주,쌀,땅콩,,
4       4           33JU                향기,단맛,,,,,,,,증류주,꿀,삼,,
5       5            52C                  향기,단맛,,,,,,,,증류주,쌀,,
6       6       DMZ240km               ,,,,바디감,,,,,기타주류,꿀,버섯,,
7       7        g12골디락스           ,,,,바디감,,,,,탁주,쌀,찹쌀,밀,,무감미료
8       8     The찾을수록시리즈                ,단맛,,청량감,,,,,,과실주,사과,,
9       9        가덕순쌀막걸리         ,단맛,신맛,청량감,바디감,,담백,,탄산,탁주,쌀,,
10     10        가을빛레드와인                ,,신맛,청량감,,,,,,과실주,포도,,
11     11        가평잣생막걸리                 ,,,청량감,바디감,,,,,탁주,쌀,,
12     12         감그린레귤러            ,단맛,신맛,청량감,,,,,,과실주,,이색전통주
13     13         감그린스페셜         ,단맛,신맛,청량감,바디감,,,,,과실주,,이색전통주
14     14       감그린아이스와인              ,단맛,,,바디감,,,,,과실주,,이색전통주
15     15           감보드카                  ,,,,바디감,목넘김,,,,증류주,,
16     16             감사             ,,,,,목넘김,담백,,,약주/청주,쌀,,선물
17     17          감아락25                    ,,,,,,,,,증류주,쌀,,가을
18     18         감악산머루주           ,단맛,신맛,청량감,바디감,,,,,과실주,머루,,
19     19            감이슬                     ,,,,,,,,,증류주,,과일류
20     20          감자술13            ,단맛,,청량감,,,,,,약주/청주,감자,,선물
21     21          감홍로백자            향기,단맛,,,바디감,,,,,증류주,쌀,약재,,
22     22          감홍로청자            향기,단맛,,,바디감,,,,,증류주,쌀,약재,,
23     23            강소주              향기,,,,바디감,,,,,증류주,쌀,,소용량
24     24             강쇠             ,,,,바디감,,,,,약주/청주,쌀,오가피,,
25     25            걍즐겨     ,단맛,신맛,청량감,바디감,,,,,탁주,쌀,찹쌀,,이색전통주
26     26         겨울소주25              향기,,,,바디감,목넘김,,,,증류주,,겨울
27     27            경기전             ,,신맛,청량감,,,,,,기타주류,보리,,탄산
28     28       계룡백일주12년  향기,단맛,,,바디감,,,,,기타주류,쌀,찹쌀,오미자,꽃,솔잎,,
29     29        계룡백일주16        ,,,,,,,,,약주/청주,쌀,찹쌀,오미자,꽃,솔잎,,

In [127]:
df.loc[df["키워드(thesool)"] == "탄산"]

Unnamed: 0  index        제품명 향기  단맛  신맛  청량감  바디감 목넘김  담백  ...  탄산    주종  \
27           27     27        경기전         신맛  청량감               ...      기타주류   
141         141    141  맑은내일발효막걸리     단맛  신맛  청량감  바디감          ...        탁주   
181         181    181      미생막걸리         신맛  청량감  바디감          ...        탁주   
229         229    229    산막생유막걸리         신맛  청량감  바디감          ...        탁주   
301         301    301        아이싱     단맛           바디감          ...        탁주   
345         345    345        오목대         신맛  청량감  바디감          ...      기타주류   
349         349    349  오희스파클링막걸리         신맛  청량감           담백  ...  탄산    탁주   
371         371    371    이동생쌀막걸리         신맛  청량감  바디감          ...        탁주   
376         376    376     인천생소성주                               ...        탁주   
385         385    385     장수생막걸리         신맛  청량감  바디감          ...        탁주   

     도수%             용량    가격                              원재료 원재료키워드  \
27     5         1000ml                보리,맥아,호프펠렛,효모,정제효소제,정제수    보리,   
141    7  750ml/1,000ml                       쌀,누룩,효소,아스파탐,정제수     쌀,   
181    6          750ml  1100              국내산쌀,누룩,효모,정제효소,정제수     쌀,   
229    6          750ml  1200                   국내산쌀,소맥분,종국,효모     쌀,   
301    4    350ml,300ml                                쌀,자몽엑기스     쌀,   
345    5         1000ml         보리,맥아,말토텍스트린,호프펠렛,효모,정제효소제,정제수    보리,   
349  8.5          500ml                    백미,건오미자,조효소제,효모,정제수   오미자,   
371    6          750ml  1300              정제수,백미,팽화미,입국,아스파탐등          
376    6          750ml  1200  쌀,팽화미,정제수,국,효모,아스파탐,효소,이소말토올리고당     쌀,   
385    6          750ml  1200                        백미,말토올리고당          

                          제조사 키워드(thesool)  \
27   농업회사법인동문거리양조장(주)(전주술로시티)           탄산   
141            농업회사법인우포의아침(주)           탄산   
181              김포금쌀탁주영농조합법인           탄산   
229            농업회사법인신탄진주조(주)           탄산   
301                       국순당           탄산   
345  농업회사법인동문거리양조장(주)(전주술로시티)           탄산   
349                      문경주조           탄산   
371                      이동주조           탄산   
376                      인천탁주           탄산   
385                  서울장수주식회사           탄산   

                                       어울리는음식(thesool)  
27   홉의 향이 아로마틱하게 올라온다. IPA를 추구한 맛이란 것을 그대로 알 수 있다....  
141                                             족발,모듬전  
181  일반 쌀 막걸리에 비해 단맛이 적은 드라이한 맛이다. 개운한 맛의 칼칼함이 특징. ...  
229  아이보리 색을 가지고 있으며 곡물향과 상큼한 향이 섞여 올라옵니다. 입에 넣으면 탄...  
301  붉은 진주빛을 가지고 있으며 잘 익은 검은 과실향이 올라옵니다. 술을 입에 넣으면 ...  
345  구워진 곡물 맛을 그대로 느낄 수 있는 발포주. 진한 에스프레소와 같은 향도 있습니...  
349  술 빛이 붉은 오미자의 색을 그대로 닮았으며 고소한 향이 처음 강하게 올라왔다 사라...  
371  쌀과 쌀 누룩을 이용해 막걸리 빛이 희고 팽화미 특유의 고소한 맛과 향미가 있는 것...  
376  원료인 팽화미에서 나오는 고소한 향이 올라오는 것이 특징입니다. 전체적으로 바디감과...  
385  일반적인 서울장수막걸리에서 느껴지는 익숙한 단맛과 과일향과 함께 상쾌한 탄산기운을 ...  

[10 rows x 21 columns]

In [107]:
lis = []
for i in dff['keyword']:
    i = re.sub(","," ", i)
    lis.append(i)
lis


[' 단맛 신맛 청량감 바디감     탁주 쌀 밀  ',
 ' 단맛 신맛 청량감 바디감     탁주 쌀 밀  저도수',
 '   청량감 바디감     탁주 쌀 땅콩  ',
 ' 단맛   바디감     탁주 쌀 땅콩  ',
 '향기 단맛        증류주 꿀 삼  ',
 '향기 단맛        증류주 쌀  ',
 '    바디감     기타주류 꿀 버섯  ',
 '    바디감     탁주 쌀 찹쌀 밀  무감미료',
 ' 단맛  청량감      과실주 사과  ',
 ' 단맛 신맛 청량감 바디감  담백  탄산 탁주 쌀  ',
 '  신맛 청량감      과실주 포도  ',
 '   청량감 바디감     탁주 쌀  ',
 ' 단맛 신맛 청량감      과실주  이색전통주',
 ' 단맛 신맛 청량감 바디감     과실주  이색전통주',
 ' 단맛   바디감     과실주  이색전통주',
 '    바디감 목넘김    증류주  ',
 '     목넘김 담백   약주/청주 쌀  선물',
 '         증류주 쌀  가을',
 ' 단맛 신맛 청량감 바디감     과실주 머루  ',
 '         증류주  과일류',
 ' 단맛  청량감      약주/청주 감자  선물',
 '향기 단맛   바디감     증류주 쌀 약재  ',
 '향기 단맛   바디감     증류주 쌀 약재  ',
 '향기    바디감     증류주 쌀  소용량',
 '    바디감     약주/청주 쌀 오가피  ',
 ' 단맛 신맛 청량감 바디감     탁주 쌀 찹쌀  이색전통주',
 '향기    바디감 목넘김    증류주  겨울',
 '  신맛 청량감      기타주류 보리  탄산',
 '향기 단맛   바디감     기타주류 쌀 찹쌀 오미자 꽃 솔잎  ',
 '         약주/청주 쌀 찹쌀 오미자 꽃 솔잎  ',
 '    바디감     기타주류 쌀 찹쌀 오미자 꽃 솔잎  ',
 '향기 단맛   바디감     기타주류 쌀 찹쌀 오미자 꽃 솔잎  ',
 '         증류주 삼  삼(蔘

In [108]:
k = pd.DataFrame(lis, columns= ['kk'])
k

kk
0        단맛 신맛 청량감 바디감     탁주 쌀 밀  
1     단맛 신맛 청량감 바디감     탁주 쌀 밀  저도수
2             청량감 바디감     탁주 쌀 땅콩  
3            단맛   바디감     탁주 쌀 땅콩  
4            향기 단맛        증류주 꿀 삼  
..                              ...
528          단맛  청량감 바디감     탁주 쌀  
529                  바디감     탁주 쌀  
530                   목넘김    기타주류  
531       단맛 신맛  바디감     탁주 쌀  무감미료
532        신맛  바디감  담백   탁주 쌀  무감미료

[533 rows x 1 columns]

In [109]:
dff['keyword'] = k['kk']
dff

index            제품명                         keyword
0        0  1000억막걸리프리바이오      단맛 신맛 청량감 바디감     탁주 쌀 밀  
1        1    1000억유산균막걸리   단맛 신맛 청량감 바디감     탁주 쌀 밀  저도수
2        2  1932새싹땅콩햅쌀막걸리           청량감 바디감     탁주 쌀 땅콩  
3        3  1932새싹땅콩흑미막걸리          단맛   바디감     탁주 쌀 땅콩  
4        4           33JU          향기 단맛        증류주 꿀 삼  
..     ...            ...                             ...
528    528         회곡생동동주          단맛  청량감 바디감     탁주 쌀  
529    529         회곡생막걸리                  바디감     탁주 쌀  
530    530            흑돈주                   목넘김    기타주류  
531    531       희양산막걸리15       단맛 신맛  바디감     탁주 쌀  무감미료
532    532        희양산막걸리9        신맛  바디감  담백   탁주 쌀  무감미료

[533 rows x 3 columns]

In [110]:
#dff.loc[0,'keyword'] = list(filter(lambda x : x in feature_list, dff.loc[0,'keyword'])
#dff

In [134]:
dff.to_csv("cbf_database.csv")

# CountVectorizer demo

In [111]:
from ast import literal_eval  # 문자열 파싱 라이브러리
from sklearn.feature_extraction.text import CountVectorizer

In [112]:
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2))  
# min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
key_mat = count_vect.fit_transform(dff['keyword'])

print(key_mat.shape)
print(key_mat)

(533, 280)
  (0, 56)	1
  (0, 143)	1
  (0, 205)	1
  (0, 91)	1
  (0, 231)	1
  (0, 62)	1
  (0, 149)	1
  (0, 209)	1
  (0, 98)	1
  (1, 56)	1
  (1, 143)	1
  (1, 205)	1
  (1, 91)	1
  (1, 231)	1
  (1, 62)	1
  (1, 149)	1
  (1, 209)	1
  (1, 98)	1
  (1, 169)	1
  (1, 246)	1
  (2, 205)	1
  (2, 91)	1
  (2, 231)	1
  (2, 209)	1
  (2, 98)	1
  :	:
  (528, 65)	1
  (529, 91)	1
  (529, 231)	1
  (529, 98)	1
  (530, 38)	1
  (530, 82)	1
  (530, 84)	1
  (531, 56)	1
  (531, 143)	1
  (531, 91)	1
  (531, 231)	1
  (531, 62)	1
  (531, 98)	1
  (531, 90)	1
  (531, 147)	1
  (531, 236)	1
  (532, 143)	1
  (532, 91)	1
  (532, 231)	1
  (532, 90)	1
  (532, 67)	1
  (532, 94)	1
  (532, 147)	1
  (532, 236)	1
  (532, 70)	1


In [113]:
count_vect2 = CountVectorizer(min_df=1, ngram_range=(1, 3))  # min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
key_mat2 = count_vect2.fit_transform(dff['keyword'])
print(key_mat2.shape)
print(key_mat2)

(533, 635)
  (0, 108)	1
  (0, 337)	1
  (0, 469)	1
  (0, 213)	1
  (0, 544)	1
  (0, 131)	1
  (0, 362)	1
  (0, 485)	1
  (0, 267)	1
  (0, 135)	1
  (0, 366)	1
  (0, 492)	1
  (1, 108)	1
  (1, 337)	1
  (1, 469)	1
  (1, 213)	1
  (1, 544)	1
  (1, 131)	1
  (1, 362)	1
  (1, 485)	1
  (1, 267)	1
  (1, 135)	1
  (1, 366)	1
  (1, 492)	1
  (1, 414)	1
  :	:
  (530, 183)	1
  (531, 108)	1
  (531, 337)	1
  (531, 213)	1
  (531, 544)	1
  (531, 131)	1
  (531, 267)	1
  (531, 212)	1
  (531, 353)	1
  (531, 134)	1
  (531, 359)	1
  (531, 549)	1
  (531, 271)	1
  (532, 337)	1
  (532, 213)	1
  (532, 544)	1
  (532, 212)	1
  (532, 153)	1
  (532, 239)	1
  (532, 353)	1
  (532, 549)	1
  (532, 355)	1
  (532, 159)	1
  (532, 242)	1
  (532, 161)	1


In [114]:
from sklearn.metrics.pairwise import cosine_similarity
key_sim = cosine_similarity(key_mat, key_mat)

print(key_sim.shape)
print(key_sim[:10])
# 대칭 행렬

(533, 533)
[[1.         0.90453403 0.62994079 ... 0.         0.66666667 0.33333333]
 [0.90453403 1.         0.56980288 ... 0.         0.60302269 0.30151134]
 [0.62994079 0.56980288 1.         ... 0.         0.37796447 0.25197632]
 ...
 [0.37796447 0.34188173 0.42857143 ... 0.         0.50395263 0.37796447]
 [0.25197632 0.22792115 0.14285714 ... 0.         0.12598816 0.        ]
 [0.73960026 0.66899361 0.41931393 ... 0.         0.46225016 0.46225016]]


In [115]:
key_sim_sorted_ind = key_sim.argsort()[:, ::-1] # ::-1 : 역순으로 정렬
print(key_sim_sorted_ind[:5])

[[  0 105 391 ...  29 381 337]
 [  1   0 105 ...  29 416 337]
 [  2 403  11 ... 234 508 415]
 [  3 264 507 ... 415  73 231]
 [  5   4 450 ... 288 291 266]]


In [128]:
title_sool = dff[dff['제품명'] == '오희스파클링막걸리']
title_sool

index        제품명                       keyword
349    349  오희스파클링막걸리    신맛 청량감   담백  탄산 탁주 오미자  탄산

In [129]:
sool_index = title_sool.index.values
sool_index

array([349], dtype=int64)

In [130]:
similar_indexes = key_sim_sorted_ind[sool_index, :10]
similar_indexes

array([[349, 249, 173,   9, 436, 215, 385, 371, 181, 275]], dtype=int64)

In [131]:
# 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
# dataframe에서 index로 사용하기 위해서 2차원 array를 1차원 array로 변경
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[349 249 173   9 436 215 385 371 181 275]


In [132]:
dff.iloc[similar_indexes]

index          제품명                        keyword
349    349    오희스파클링막걸리     신맛 청량감   담백  탄산 탁주 오미자  탄산
249    249       선호생막걸리      신맛 청량감 바디감  담백  탄산 탁주 쌀  
173    173  문경주조오미자생막걸리       신맛  바디감  담백  탄산 탁주 오미자  
9        9      가덕순쌀막걸리   단맛 신맛 청량감 바디감  담백  탄산 탁주 쌀  
436    436  청남대블루베리생막걸리     단맛  청량감   담백  탄산 탁주 쌀 베리  
215    215     복순도가손막걸리        신맛 청량감 바디감    탄산 탁주  파티
385    385       장수생막걸리          신맛 청량감 바디감     탁주  탄산
371    371      이동생쌀막걸리          신맛 청량감 바디감     탁주  탄산
181    181        미생막걸리        신맛 청량감 바디감     탁주 쌀  탄산
275    275         술공방9      단맛   바디감  담백  탄산 탁주 쌀 밀